apiVersion: v2
name: magda-function-esri-url-processor
description: A Helm chart for Magda Openfaas function
version: "1.1.0"
kubeVersion: ">= 1.14.0-0"
home: "https://github.com/magda-io/magda-function-esri-url-processor"
sources:
  [
    "https://github.com/magda-io/magda-function-esri-url-processor"
  ]
annotations:
  magdaModuleType: "urlProcessor"
dependencies:
  - name: magda-common
    version: "1.0.0-alpha.4"
    repository: "https://charts.magda.io"
